name: adventOfCode2020
version: 0.1.0.0
github: "joanllenas/adventOfCode2020"
license: BSD3
author: "Joan Llenas Masó"
maintainer: "example@example.com"
copyright: "2020 Joan Llenas Masó"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/joanllenas/adventOfCode2020#readme>

dependencies:
  - base >= 4.7 && < 5
  - directory
  - parsec
  - QuickCheck
  - hspec

library:
  source-dirs: src

executables:
  adventOfCode2020-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventOfCode2020

tests:
  adventOfCode2020-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventOfCode2020
